var bgStart;
var gameState = "start";
var girlImg,boyImg,cloudImg, cloudImg1;
var countButton = 1;
var next,nextImg;
var start,startImg;
var levelImg;
var l1,l2,l3,l4,l1Img,l2Img,l3Img,l4Img;
var lock1,lock2,lock3;
var mario,marioAni,marioStanding,marioBack,marioPower,mariodead,mariostar,marioSpace,marioSpaceProtected;
var distance = 0;
var skybg,ground1,ground2;
var mousePressedl1 = false;
var mousePressedl2 = false;
var mousePressedl3 = false;
var g1Img,g2Img,g1Group;
var key1,key1Img,key2,key3;
var restart,nextLevel2,restartImg,nextLevel2Img,restart2;
var mushroom1Ani,mushroom2Ani,mushroom1Stand,mushroom2Stand;
var mushroom1Group;
var cherryImg,cherryGroup;
var coinImg,coinG1,coinG2,coinG3;
var score = 0;
var invisiGround1,invisiGround2Group;
var time = 0;
var forestbg,wall1,wall2,wall3,wall4,wall5,wall6,wall7,wall8,wall9,wall10,wall11,wall12,wall13,wall14,wall15,wall16,wall17,wall18,wall19;
var crow,crowImg1,crowImg2,gorilla,gorillaImg1,gorillaImg2,dino,dinoImg1,dinoImg2,flamingo,flamingoImg1,flamingoImg2,bat,batImg,potion,potionImg,potionGroup;
var line1,line2,line3,line4;
var levelup,nextLevel3,nextLevel4;
var spacebg,laserGroup,enemyLaserGroup1,enemyLaserGroup2,enemy1Img,enemy2Img,enemy1Group,enemy2Group;
var laser1,laser2,laser3;
var waterbg,marioWater1,marioWater2,fish1Img,fish2Img,crabImg,octopusImg,fish1Group,fish2Group,crabGroup,octopusGroup;
var treasure1,treasure2,treasure3,key4,key5,key6,treasure1Img,treasure2Img,treasure3Img,opent1,opent2,opent3;
var marioDance,camXl4,camYl4;
var level1State = true;
var level2State = true;
var level = 1;
