function loadImages(){
    bgStart = loadImage("IMAGES/bg start.png")
    girlImg = loadImage("IMAGES/person1.png");
    boyImg = loadImage("IMAGES/person2.png");
    cloudImg = loadImage("IMAGES/cloud.png");
    nextImg = loadImage("IMAGES/next level.png");
    cloudImg1 = loadImage("IMAGES/cloud1.png");
    startImg = loadImage("IMAGES/start_button.png");
    levelImg = loadImage("IMAGES/levet bg.png");
    l1Img = loadImage("IMAGES/level1.png");
    l2Img = loadImage("IMAGES/level2.png");
    l3Img = loadImage("IMAGES/level3.png");
    l4Img = loadImage("IMAGES/level4.png");
    marioBack = loadAnimation("IMAGES/MARIO/m4.png","IMAGES/MARIO/m5.png","IMAGES/MARIO/m6.png")
    marioAni = loadAnimation("IMAGES/MARIO/m1.png","IMAGES/MARIO/m2.png","IMAGES/MARIO/m3.png")
    marioStanding = loadAnimation("IMAGES/MARIO/m1.png");

    skybg = loadImage("IMAGES/sky bg.jpg");
    // groundImg = loadImage("IMAGES/ground.png");
    g1Img = loadImage("IMAGES/sky/g1.png");
    key1Img = loadImage("IMAGES/TEASURE/display key.png");
    restartImg = loadImage("IMAGES/restart.png");
    nextLevel2Img = loadImage("IMAGES/next level.png");
    // restartPoster = loadImage("IMAGES/restart poster.png");
    mushroom1Ani = loadAnimation("IMAGES/sky/m1.png","IMAGES/sky/m2.png","IMAGES/sky/m3.png");
    //mushroom2Ani = loadAnimation("IMAGES/sky/m4.png","IMAGES/sky/m5.png","IMAGES/sky/m6.png")
   // mushroom2Stand = loadAnimation("IMAGES/sky/m4.png");
    mushroom1Stand = loadAnimation("IMAGES/sky/m1.png");
    cherryImg = loadImage("IMAGES/cherry.png");
    coinImg = loadImage("IMAGES/coin1.png")
    forestbg = loadImage("IMAGES/forest bg.jpg");
    marioPower = loadAnimation("IMAGES/MARIO/marioPower.png");
    crowImg1 = loadAnimation("IMAGES/forest/crow1.png");
    crowImg2 = loadAnimation("IMAGES/forest/crow2.png");
    gorillaImg1 = loadAnimation("IMAGES/forest/gorilla1.png","IMAGES/forest/gorilla2.png");
    gorillaImg2 = loadAnimation("IMAGES/forest/gorilla3.png","IMAGES/forest/gorilla4.png");
    dinoImg1 = loadAnimation("IMAGES/forest/dino1.png","IMAGES/forest/dino2.png","IMAGES/forest/dino3.png");
    dinoImg2 = loadAnimation("IMAGES/forest/dino4.png","IMAGES/forest/dino5.png","IMAGES/forest/dino6.png");
    flamingoImg1 = loadAnimation("IMAGES/forest/flamingo1.png","IMAGES/forest/flamingo2.png","IMAGES/forest/flamingo3.png");
    flamingoImg2 = loadAnimation("IMAGES/forest/flamingo4.png","IMAGES/forest/flamingo5.png","IMAGES/forest/flamingo6.png")
    batImg = loadAnimation("IMAGES/forest/bat1.png","IMAGES/forest/bat2.png");
    potionImg = loadImage("IMAGES/potion.png");
    levelup = loadImage("IMAGES/levelup.png");
    mariodead = loadAnimation("IMAGES/MARIO/mariodie.png");
    mariostar = loadAnimation("IMAGES/MARIO/marioStar.png");
    spacebg = loadImage("IMAGES/space bg.jpg");
    marioSpace = loadAnimation("IMAGES/space/space ship.png");
    laser3 = loadImage("IMAGES/space/laser3.png");
    laser2 = loadImage("IMAGES/space/laser2.png");
    laser1 = loadImage("IMAGES/space/laser1.png");
    enemy1Img = loadImage("IMAGES/space/enemy ship.png");
    enemy2Img = loadImage("IMAGES/space/enemyship2.png");
    marioSpaceProtected = loadAnimation("IMAGES/space/protected ship.png");
    waterbg = loadImage("IMAGES/water bg.jpg");
    marioWater1 = loadAnimation("IMAGES/MARIO/marioWater1.png");
    marioWater2 = loadAnimation("IMAGES/MARIO/marioWater2.png");
    fish1Img = loadAnimation("IMAGES/water/fish1.png","IMAGES/water/fish2.png","IMAGES/water/fish3.png");
    fish2Img = loadAnimation("IMAGES/water/fish4.png","IMAGES/water/fish5.png","IMAGES/water/fish6.png")
    crabImg = loadImage("IMAGES/water/crab.png");
    octopusImg = loadAnimation("IMAGES/water/octopus1.png","IMAGES/water/octopus2.png");
    treasure1Img = loadAnimation("IMAGES/TEASURE/t1.png");
    treasure2Img = loadAnimation("IMAGES/TEASURE/t2.png");
    treasure3Img = loadAnimation("IMAGES/TEASURE/t3.png");
    opent1 = loadAnimation("IMAGES/TEASURE/open t1.png");
    opent2 = loadAnimation("IMAGES/TEASURE/open t2.png");
    opent3 = loadAnimation("IMAGES/TEASURE/open t3.png");
    marioDance = loadAnimation("IMAGES/MARIO/marioDancing1.png","IMAGES/MARIO/marioDancing2.png")
}